### PR TITLE
Animal database

### PR DESCRIPTION
**Pull request by eudondian**
1. Created Table
2. Inserted Data on the table
3. Wrote queries following quests:

- Find all animals whose name ends in "mon".
- List the name of all animals born between 2016 and 2019.
- List the name of all animals that are neutered and have less than 3 escape attempts.
- List the date of birth of all animals named either "Agumon" or "Pikachu".
- List name and escape attempts of animals that weigh more than 10.5kg
- Find all animals that are neutered.
- Find all animals not named Gabumon.
- Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)

Names ending in mon

DOB btw 2016 and 2019

Neutered and les than 3 escape attempt

DOB for Agu and Pika

names and escape attempt

neutered animals

not Gabumon

not Gabumon

Weight btw

Updated README file

Updated README 

Updated README

### CODE REVIEW

**Review by nahnahdev — CHANGES_REQUESTED** [review]
## Project Status: CHANGES REQUIRED :recycle: 
Hi @eudondian , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- All required files present :heavy_check_mark: 
- Each file contains its corresponding data :heavy_check_mark: 
- All queries return the right results :heavy_check_mark:  

## Required Changes ♻️
- [ ] Good job so far @eudondian There are just a few  changes that need to be made in your README and you'll be on your way to the next project :+1: 
- [ ] I noticed that you have two `Getting Started sections` in your README. I will suggest you keep just one :+1: 
- [ ] I also noticed that your MIT license link leads to an error page. Kindly fix that as well :+1: 
image
- [ ] It looks like you have all the headers present in your README but you haven't customized it to suit this project so they still contain the default contents as seen in the Microverse Readme Template. Please fix this so your README can be professional and contain content relevant to this project :wink: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Esther, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good job writing the queries

 ## Required Changes ♻️
- [ ] It looks like the changes you made aren't pushed to your GitHub repo after the change request from the previous CR. please make sure to push your changes before requesting another review.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @eudondian,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project with README that contain section descriptions. Some sections of your README are also not yet customized. The link in the live demo section is invalid, Kindly complete this text: "[your_project__name] is a...". Kindly implement the changes on the documentation and ensure you are thorough.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by osamaashraf6 — APPROVED** [review]
Hi @eudondian 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
MinionsGIF (2)

## Highlights🎉🎉
- [ ] Good using the SQL commands 🚀
- [ ] Good putting screenshots of queries results to the pull request description👌
- [ ] Good at putting the SQL commands at the expected Project specific files like schema and data....💯


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
